<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.6</version>
        <relativePath/>
    </parent>

    <groupId>fr.lpadmin</groupId>
    <artifactId>lpadmin-facture</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>fr-lpadmin-facture</name>
    <description>Facture Extract App</description>

    <properties>
        <java.version>25</java.version>
        <poi.version>5.5.1</poi.version>
        <pdfbox.version>3.0.2</pdfbox.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>${poi.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>${poi.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>pdfbox</artifactId>
            <version>${pdfbox.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-json</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-restclient</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>

              <plugin>
                 <groupId>org.apache.maven.plugins</groupId>
                 <artifactId>maven-antrun-plugin</artifactId>
                 <version>3.1.0</version>
                 <executions>
                    <execution>
                        <id>download-ubl-xsd-set</id>
                        <phase>initialize</phase>
                        <goals>
                           <goal>run</goal>
                        </goals>
                        <configuration>
                           <target>
                              <mkdir dir="${project.build.directory}/generated-resources/xsd/maindoc"/>
                              <mkdir dir="${project.build.directory}/generated-resources/xsd/common"/>

                              <get src="https://docs.oasis-open.org/ubl/cs-UBL-2.0/xsd/maindoc/UBL-Invoice-2.0.xsd"
                                  dest="${project.build.directory}/generated-resources/xsd/maindoc/UBL-Invoice-2.0.xsd"
                                  usetimestamp="true"/>

                              <get src="https://docs.oasis-open.org/ubl/cs-UBL-2.0/xsd/common/CCTS_CCT_SchemaModule-2.0.xsd"
                                  dest="${project.build.directory}/generated-resources/xsd/common/CCTS_CCT_SchemaModule-2.0.xsd"
                                  usetimestamp="true"/>
                              <get src="https://docs.oasis-open.org/ubl/cs-UBL-2.0/xsd/common/CodeList_CurrencyCode_ISO_7_04.xsd"
                                  dest="${project.build.directory}/generated-resources/xsd/common/CodeList_CurrencyCode_ISO_7_04.xsd"
                                  usetimestamp="true"/>
                              <get src="https://docs.oasis-open.org/ubl/cs-UBL-2.0/xsd/common/CodeList_LanguageCode_ISO_7_04.xsd"
                                  dest="${project.build.directory}/generated-resources/xsd/common/CodeList_LanguageCode_ISO_7_04.xsd"
                                  usetimestamp="true"/>
                              <get src="https://docs.oasis-open.org/ubl/cs-UBL-2.0/xsd/common/CodeList_MIMEMediaTypeCode_IANA_7_04.xsd"
                                  dest="${project.build.directory}/generated-resources/xsd/common/CodeList_MIMEMediaTypeCode_IANA_7_04.xsd"
                                  usetimestamp="true"/>
                              <get src="https://docs.oasis-open.org/ubl/cs-UBL-2.0/xsd/common/CodeList_UnitCode_UNECE_7_04.xsd"
                                  dest="${project.build.directory}/generated-resources/xsd/common/CodeList_UnitCode_UNECE_7_04.xsd"
                                  usetimestamp="true"/>
                              <get src="https://docs.oasis-open.org/ubl/cs-UBL-2.0/xsd/common/UBL-CommonAggregateComponents-2.0.xsd"
                                  dest="${project.build.directory}/generated-resources/xsd/common/UBL-CommonAggregateComponents-2.0.xsd"
                                  usetimestamp="true"/>
                              <get src="https://docs.oasis-open.org/ubl/cs-UBL-2.0/xsd/common/UBL-CommonBasicComponents-2.0.xsd"
                                  dest="${project.build.directory}/generated-resources/xsd/common/UBL-CommonBasicComponents-2.0.xsd"
                                  usetimestamp="true"/>
                              <get src="https://docs.oasis-open.org/ubl/cs-UBL-2.0/xsd/common/UBL-CommonExtensionComponents-2.0.xsd"
                                  dest="${project.build.directory}/generated-resources/xsd/common/UBL-CommonExtensionComponents-2.0.xsd"
                                  usetimestamp="true"/>
                              <get src="https://docs.oasis-open.org/ubl/cs-UBL-2.0/xsd/common/UBL-CoreComponentParameters-2.0.xsd"
                                  dest="${project.build.directory}/generated-resources/xsd/common/UBL-CoreComponentParameters-2.0.xsd"
                                  usetimestamp="true"/>
                              <get src="https://docs.oasis-open.org/ubl/cs-UBL-2.0/xsd/common/UBL-ExtensionContentDatatype-2.0.xsd"
                                  dest="${project.build.directory}/generated-resources/xsd/common/UBL-ExtensionContentDatatype-2.0.xsd"
                                  usetimestamp="true"/>
                              <get src="https://docs.oasis-open.org/ubl/cs-UBL-2.0/xsd/common/UBL-QualifiedDatatypes-2.0.xsd"
                                  dest="${project.build.directory}/generated-resources/xsd/common/UBL-QualifiedDatatypes-2.0.xsd"
                                  usetimestamp="true"/>
                              <get src="https://docs.oasis-open.org/ubl/cs-UBL-2.0/xsd/common/UnqualifiedDataTypeSchemaModule-2.0.xsd"
                                  dest="${project.build.directory}/generated-resources/xsd/common/UnqualifiedDataTypeSchemaModule-2.0.xsd"
                                  usetimestamp="true"/>
                           </target>
                        </configuration>
                    </execution>
                 </executions>
              </plugin>

            <plugin>
                <groupId>org.jvnet.jaxb</groupId>
                <artifactId>jaxb-maven-plugin</artifactId>
                <version>4.0.8</version>
                <executions>
                    <execution>
                        <id>generate-ubl-invoice-beans</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <schemaDirectory>${project.build.directory}/generated-resources/xsd/maindoc</schemaDirectory>
                            <schemaIncludes>
                                <include>UBL-Invoice-2.0.xsd</include>
                            </schemaIncludes>
                            <generateDirectory>${project.build.directory}/generated-sources/xjc</generateDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.3.1</version>
                <executions>
                    <execution>
                        <id>copy-ubl-schemas-to-classpath</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.outputDirectory}/ubl/xsd</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.build.directory}/generated-resources/xsd</directory>
                                    <includes>
                                        <include>**/*.xsd</include>
                                    </includes>
                                    <filtering>false</filtering>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
                
                <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.7.1</version>
                <executions>
                    <execution>
                        <id>assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>src/main/assemble/assembly.xml</descriptor>
                            </descriptors>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    

</project>
