

app.lmstudio.baseUrl=http://IDLLF5X5B44.local:1234
#app.lmstudio.model=lfm2.5-vl-450m
#app.lmstudio.model=qwen2_0.5b_instruct_invoice_parser_v2
app.lmstudio.model=qwen3.5-2b
app.lmstudio.connect-timeout-ms=5000
app.lmstudio.read-timeout-ms=180000

app.pdf.input.dir=/workspaces/facture/input/
app.template.file=/workspaces/facture/template/TEMPLATE.xlsx
app.output.file=/workspaces/facture/output/output.xlsx

app.prompt.file=/workspaces/facture/facture-bo/testconfig/prompt/prompt.txt
app.prompt.includeImg=true
app.prompt.includeText=false


logging.level.fr.lpadmin.facture=DEBUG
#logging.level.org.springframework.web.client=DEBUG
#logging.level.org.springframework.http=DEBUG