

app.lmstudio.model=qwen3.5-2b
app.lmstudio.connect-timeout-ms=5000
app.lmstudio.read-timeout-ms=180000

app.pdf.input.dir=C:\\platform\\facture\\input\\
app.template.file=C:\\platform\\facture\\template\\TEMPLATE.xlsx
app.output.file=C:\\platform\\facture\\output\\output.xlsx

app.prompt.file=C:\\platform\\facture\\prompt\\prompt.txt
app.prompt.includeImg=true
app.prompt.includeText=false


logging.level.fr.lpadmin.facture=DEBUG
#logging.level.org.springframework.web.client=DEBUG
#logging.level.org.springframework.http=DEBUG
